export const options = {
    lines: 9,
    length: 8,
    width: 5,
    radius: 8,
    scale: 1.00,
    corners: 1,
    color: '#000',
    opacity: 0.4,
    rotate: 0,
    direction: 1,
    speed: 1,
    trail: 60,
    fps: 20,
    zIndex: 2e9,
    top: '50%',
    left: '50%',
    shadow: false,
    hwaccel: false,
    position: 'absolute'
};