server: 
  port: 8081
  
#server registery under this name
spring:
  application:
    name: login-microservices
    

#Discovery server access
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
      healthcheck:
      enabled: true
      lease: 
       duration: 5
     
#Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
sql: 
    db: 
        username: root
        password: root
        url: "jdbc:mysql://localhost:3306/coe_db"
        driver-class-name: "com.mysql.jdbc.Driver" 
    
